apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: hello-node
  name: hello-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: hello-node
    spec:
      containers:
      - image: kanatakita/hello-node:v1
        name: hello-node
        ports:
        - containerPort: 8080

