kind: Service
apiVersion: v1
metadata: 
  name: prometheus
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  labels: 
    kubernetes.io/name: "Prometheus"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec: 
  ports: 
    - name: http 
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector: 
    k8s-app: prometheus
  type: LoadBalancer
