---
apiVersion: v1
kind: Service
metadata:
  name: kanata-test
  namespace: test
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - port: 8081
aaa
      protocol: TCP
      targetPort: 80
  selector:
    parentPipelineStageId: ${ trigger.parentPipelineStageId }

---
apiVersion: v1
kind: Service
metadata:
  name: kanata
  namespace: test
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
  selector:
    app: kanata

