apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: cinder
    #volume.alpha.kubernetes.io/storage-provisioner: kubernetes.io/cinder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder
  resources:
    requests:
      storage: 3Gi

