---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: kanata
  name: kanata
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      eventId: ${ trigger.eventId }
  template:
    metadata:
      labels:
        eventId: ${ trigger.eventId }
        cluster: for-kanata
    spec:
      containers:
      - name: kanata
        image: 'kanatakita/print-tag:${parameters["POD_VERSION"]}'
        ports:
        - containerPort: 8080

