kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foo
rules:
  - verbs: ["get", "list", "watch"]
    apiGroups: [""]
    resources: ["pods", "pods/exec"]
  - verbs: ["*"]
    nonResourceURLs: ["/version", "/api", "/api/*", "/apis", "/apis/*"]
