---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hello-world
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-world
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
