---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        tag: ${ trigger.eventId }
    spec:
      containers:
      - image: kanatakita/print-tag:${ trigger.tag }
        name: hello-world
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-test
spec:
  hosts:
  - "*"
  gateways:
  - hello-world
  http:
  - match:
    - uri:
        prefix: "/test"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: hello-world.default.svc.cluster.local
        subset: ${ trigger.eventId }
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-world-${ trigger.eventId }
  labels:
    tag: ${ trigger.eventId }
spec:
  host: hello-world.default.svc.cluster.local
  subsets:
  - name: ${ trigger.eventId }
    labels:
      tag: ${ trigger.eventId }
